### ISSUE TITLE
Contract doesn't send back jettons

### ISSUE THREAD

**Issue by Blemflarck** [logvik/ton-ico-on-func#1]
Deployed the contract to Testnet but for some reason buying functionality only works for admin from terminal, if I try to send transaction to ICO address from another testnet wallet or via generated link it accepts the transactions but sends nothing back, any idea how to fix that?

**Comment by logvik** [comment]
Please provide the address for the deployed smart contract to check on Testnet. Do you send 
```
buy#402eff0b query_id:uint64 = InternalMsgBody;
```
message?

Because maybe the reason is in the fact that you send
```
mint#4fda1e51 query_id:uint64 to_address:MsgAddress jetton_amount:(VarUInteger 16) forward_ton_amount:(VarUInteger 16) total_ton_amount:(VarUInteger 16)
          = InternalMsgBody;
```
message. This is available only for the admin.

**Comment by Blemflarck** [comment]
Hi, thank you for your reply, here's the deployed ICO contract: https://testnet.tonscan.org/address/EQC1FKZNzLVVmVN-_nmxEjk0T06XcpLHXMfBEvHYChEHKMTn,

I send TON via link generated by controller, like ton://transfer/EQC1FKZNzLVVmVN-_nmxEjk0T06XcpLHXMfBEvHYChEHKMTn?amount=200000000&bin=te6cckEBAQEADwAAGVjKU2EAAAAAAAAAAMDCRD2b, but it returned "buying failed". At the same time if I connect tonkeeper in terminal as admin and then press buy and confirm the transaction, it returns jettons. I also tried to send ton directly to ICO contract without any luck.

**Comment by logvik** [comment]
As I can see you have sent the right message just once - https://testnet.tonviewer.com/kQC1FKZNzLVVmVN-_nmxEjk0T06XcpLHXMfBEvHYChEHKH9t?section=holders -> this owner https://testnet.tonviewer.com/0QCPQZJCtijrz0yN9Cl_dwBE9Mew36TrljV0rbCql-6kJhb_c -> https://testnet.tonviewer.com/transaction/3b0c1c04f91b0657d9c4076f65f8da02e6912598e8c45277968db2159c2c836d 
Code operation is 0x402eff0b 
From above message - buy#402eff0b query_id:uint64 = InternalMsgBody;
You can't just send TON to ICO smart contract and receive jettons back, you must to compose the special message, as you did it already the one time before, and send this with TON amount.

**Comment by Blemflarck** [comment]
II think I now get what's the issue. Thank you for your help!
