### ISSUE TITLE
UKWN instead of token name 

### ISSUE THREAD

**Issue by Blemflarck** [logvik/ton-ico-on-func#2]
After contract deployment minted tokens displayed in tonkeeper as "Unknown Token" with "UKWN" symbol, interestingly that on tonscan it clearly can read metadata and if we go to jetton contract itself - name, symbol, description and even image are displayed correctly, however if we go to wallets that hold minted tokens they are also displayed as "Unknown Token". Anyone knows what could be the problem?

**Comment by logvik** [comment]
Tonkeeper has own whitelist for all jettons. You need to pass their procedure to solve this issue.

**Comment by Blemflarck** [comment]
I'm not sure if that's tonkeeper issue, because on tonscan it displayed correctly if we go to the contract itself: https://testnet.tonscan.org/jetton/EQC1FKZNzLVVmVN-_nmxEjk0T06XcpLHXMfBEvHYChEHKMTn, but if we go to holders and then to jettons it's displayed as "unknown" https://testnet.tonscan.org/address/0QDAAON_lNBFKexjgdFnYgiAkX1MRKLS5CJV8dw_bxFVhBmM#tokens, I tried to mint tokens via tonraffles and they meta displayed correctly even though they also labeled as "unverified".

**Comment by logvik** [comment]
100% related to tonkeeper, you can search the same issue here [@ton_dev chat](https://t.me/tondev_eng)

**Comment by Blemflarck** [comment]
Thanks, I'll look into it.
